# -*- coding: utf-8 -*-
"""prototype_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X46BCEh56zmU1MxbTUO5yMC38SswgTwn
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns

# Title of the app
st.title("Who is likely to chrun - and when?")

# Cached function to read CSVs
@st.cache_data(show_spinner="Parsing uploaded data...")
def load_csv_file(uploaded_file):
    if uploaded_file is None:
        return None
    return pd.read_csv(uploaded_file)

# Sidebar section for file inputs
st.sidebar.header("Data Import")
st.sidebar.markdown("Upload all 4 CSV files to run analysis.")

sf_file = st.sidebar.file_uploader("1. Salesforce Data", type=["csv"])
omni_file = st.sidebar.file_uploader("2. Omni Data", type=["csv"])
pendo_file = st.sidebar.file_uploader("3. Pendo Data", type=["csv"])
zendesk_file = st.sidebar.file_uploader("4. Zendesk Support Data", type=["csv"])

# Load files into cache
df_sf = load_csv_file(sf_file)
df_omni = load_csv_file(omni_file)
df_pendo = load_csv_file(pendo_file)
df_zendesk = load_csv_file(zendesk_file)

# List of loaded DataFrames for quick validation
all_dfs = [df_sf, df_omni, df_pendo, df_zendesk]
loaded_count = sum(1 for df in all_dfs if df is not None)

# Main Page Area
if loaded_count == 4:
    st.success("All 4 data sources loaded successfully!")
else:
    st.info(f"Please upload all 4 files using the sidebar to begin analysis. ({loaded_count}/4 loaded)")

    # Show status list in main view 
    st.markdown("### Missing Datasets:")
    st.markdown(f"- **Salesforce Data:** {'Ready' if df_sf is not None else 'Pending upload'}")
    st.markdown(f"- **Omni Data:** {'Ready' if df_omni is not None else 'Pending upload'}")
    st.markdown(f"- **Pendo Data:** {'Ready' if df_pendo is not None else 'Pending upload'}")
    st.markdown(f"- **Support Data:** {'Ready' if df_zendesk is not None else 'Pending upload'}")

# Ensures that all dataframes exist before processing
if all(df is not None for df in [df_sf, df_omni, df_pendo, df_zendesk]):

    # Standardize 'customer_id' across all datasets
    dfs = [df_sf, df_omni, df_pendo, df_zendesk]
    for dataset in dfs:
        if 'customer_id' in dataset.columns:
            dataset['customer_id'] = dataset['customer_id'].astype(str).str.strip().str.upper()

    # Sequential Outer Merge
    df = df_sf.merge(df_omni, on='customer_id', how='outer') \
              .merge(df_pendo, on='customer_id', how='outer') \
              .merge(df_zendesk, on='customer_id', how='outer')

    # Vectorized Risk Score Calculation
    conditions = [
        (df['days_to_renewal'] <= 30) & (df['usage_change_90d_pct'] <= -25.0),
        (df['days_to_renewal'] <= 90) & (df['usage_change_90d_pct'] <= 5.0)
    ]
    levels = ['High', 'Medium']
    
    # Assigns 'Low' as default if neither condition above is met
    df['risk_score'] = np.select(conditions, levels, default='Low')

    # --- TOP SECTION: Visual Dashboard ---
    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("Risk Score Distribution")
        
        # Color palette map for risk tiers
        color_map = {
            "High": "#EF553B",    # Red
            "Medium": "#FECB52",  # Yellow/Orange
            "Low": "#00CC96"      # Green
        }

        # Plotly Pie Chart
        fig = px.pie(
            df,
            names='risk_score',
            title='Percentage of Customers by Risk Level',
            color='risk_score',
            color_discrete_map=color_map,
            hole=0.4  # Creates a clean donut chart style
        )
        fig.update_traces(textinfo='percent+label+value', hovertemplate="%{label}: %{value} customers (%{percent})")
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Key Metrics")
        total_cust = len(df)
        high_risk_count = len(df[df['risk_score'] == 'High'])
        med_risk_count = len(df[df['risk_score'] == 'Medium'])
        
        st.metric("Total Customers", f"{total_cust:,}")
        st.metric("High Risk Customers", f"{high_risk_count:,}", delta=f"{high_risk_count/total_cust:.1%}", delta_color="inverse")
        st.metric("Medium Risk Customers", f"{med_risk_count:,}", delta=f"{med_risk_count/total_cust:.1%}", delta_color="off")

    st.divider()

# -- Total Revenue at Risk
    st.subheader("By Annual Recurring Revneue (ARR)")
    
    # Create logical revenue tiers
    revenue_bins = [0, 5000, 10000, 50000, 100000]
    revenue_labels = ['$0-5k', '$5k-10k', '$10k-50k', '$100k+'] 

    df['revenue_tier'] = pd.cut(df['annual_revenue'], bins=revenue_bins, labels=revenue_labels)
    
    # Group data
    df_grouped = df.groupby(["revenue_tier", "risk_score"], observed=False)["annual_revenue"].sum().reset_index()

    # Calculate total revenue per tier for top labels
    totals = df_grouped.groupby("revenue_tier", observed=False)["annual_revenue"].sum().reset_index()

    # Create interactive stacked bar chart
    fig = px.bar(
        df_grouped,
        x="revenue_tier",
        y="annual_revenue",
        color="risk_score",
        title="Total Recurring Revenue (ARR) Portfolio at Risk",
        labels={
            "revenue_tier": "Customer Revenue Tier",
            "annual_revenue": "Total Portfolio Value ($)",
            "risk_score": "Risk Level"
        },
        color_discrete_map={
            "High": "#EF553B",
            "Medium": "#FECB52",
            "Low": "#00CC96"
        }
    )

    # Add total labels on top of each bar
    for _, row in totals.iterrows():
        if row["annual_revenue"] > 0:
            rev = row["annual_revenue"]
            label_text = f"${rev/1e6:.1f}M" if rev >= 1e6 else f"${rev/1e3:.0f}K" if rev >= 1e3 else f"${rev:,.0f}"
    
            fig.add_annotation(
                x=row["revenue_tier"],
                y=row["annual_revenue"],
                text=f"<b>{label_text}</b>",
                showarrow=False,
                yshift=10, 
                font=dict(size=12, color="white")
            )

    fig.update_layout(
        barmode="stack",
        xaxis_title="Customer Revenue Tier",
        yaxis_title="Total Portfolio Value ($)",
        yaxis_tickprefix="$",
        legend_title="Risk Level",
        margin=dict(t=60) 
    )
    st.plotly_chart(fig, use_container_width=True)
    st.divider()

# -- Accounts at risk by days to renewal
    st.subheader("By Days to renewal")

    # Create logical renewal tiers
    renewal_days_bins = [-1, 30, 60, 90, float('inf')]
    renewal_days_labels = ['0-30d', '31-60d', '61-90d', '90d+']

    # Group data by days_to_renewal
    df['renewal_tier'] = pd.cut(df['days_to_renewal'], bins=renewal_days_bins, labels=renewal_days_labels)

    # Pivot and aggregate data to get customer counts per cell
    matrix_data = pd.crosstab(df['renewal_tier'], df['risk_score'])

    # Reorder columns & index logically
    risk_order = [col for col in ['High', 'Medium', 'Low'] if col in matrix_data.columns]
    matrix_data = matrix_data[risk_order]

    # Create interactive Heatmap
    fig = px.imshow(
        matrix_data.values,
        x=matrix_data.columns,         # Risk Scores ('High', 'Medium', 'Low')
        y=matrix_data.index.astype(str),# Renewal Tiers ('0-30d', '31-60d', ...)
        text_auto=True,               
        color_continuous_scale="YlOrRd",# Yellow -> Orange -> Red scale
        aspect="auto",
        title="Customer Count by Renewal Window & Risk Score"
    )
    
    fig.update_layout(
        xaxis_title="Risk Level",
        yaxis_title="Renewal Timeframe",
        coloraxis_showscale=False     
    )
    
    st.plotly_chart(fig, use_container_width=True)
    st.divider()

# --- BOTTOM SECTION: Filtered Data Table ---
    st.subheader("Customer Details")
    
    # Filter only specific columns to display on screen
    display_columns = [
        "risk_score",
        "customer_id", 
        "customer_name", 
        "renewal_date", 
        "days_to_renewal", 
        "annual_revenue"
    ]
    
    # Keep only columns that exist in the merged dataframe
    final_cols = [col for col in display_columns if col in df.columns]
    df_display = df[final_cols]

    # Column Configuration & Display
    config = {
        "risk_score": st.column_config.TextColumn("Risk Score"),
        "customer_id": st.column_config.TextColumn("Customer ID", width="medium"),
        "customer_name": st.column_config.TextColumn("Customer Name", width="medium"),
        "renewal_date": st.column_config.DateColumn("Renewal Date", format="MMM, DD YYYY"),
        "days_to_renewal": st.column_config.NumberColumn("Days to Renewal", format="%d days"),
        "annual_revenue": st.column_config.NumberColumn("Annual Revenue ($)", format="$%d")
    }

    st.subheader("Customer Risk Summary")
    st.dataframe(df_display, width="stretch", use_container_width=True, column_config=config)

else:
    st.info("Please upload all required CSV files to run the merge and risk calculation.")

