# -*- coding: utf-8 -*-
"""prototype_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X46BCEh56zmU1MxbTUO5yMC38SswgTwn
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Title of the app
st.title("Who is likely to chrun - and when?")

# Instructions of the app
st.markdown("Upload all required reports.")

# Upload Salesforce report
sf_file = st.file_uploader("Upload the Salesforce Report")
df_sf = pd.read_csv(sf_file)

# Upload Omni report
omni_file = st.file_uploader("Upload the Omni Report")
df_omni = pd.read_csv(omni_file)

# Upload Pendo report
pendo_file = st.file_uploader("Upload the Pendo Report")
df_pendo = pd.read_csv(pendo_file)

# Upload Zendesk report
zendesk_file = st.file_uploader("Upload the Zendesk Report")
df_zendesk = pd.read_csv(zendesk_file)

# Merge all input files on account ID
df = pd.merge(df_sf, df_omni, on='customer_id', how='outer')
df = pd.merge(df, df_pendo, on='customer_id', how='outer')
df = pd.merge(df, df_zendesk, on='customer_id', how='outer')

def generate_risk_score(df):
  if df['days_to_renewal'] <= 30 and df['usage_change_90d_pct'] <= -25.0:
    df['risk_score'] = 'High';
  elif df['days_to_renewal'] <= 90 and df['usage_change_90d_pct'] <= 5.0:
    df['risk_score'] = 'Medium';
  else:
    df['risk_score'] = 'Low'

  return df

# Display dataframe
df = df.apply(generate_risk_score, axis=1)

config = {
    "customer_id": st.column_config.TextColumn("Customer ID", width="medium"),
    "customer_name": st.column_config.TextColumn("Customer Name", width="medium"),
    "renewal_date": st.column_config.DateColumn("Renewal Date", format="MMM, DD YYYY"),
    "days_to_renewal": st.column_config.NumberColumn("Days to Renewal"),
    "annual_revenue": st.column_config.NumberColumn("Annual Revenue ($)"),
    "risk_score": st.column_config.NumberColumn("Risk Score")
}

st.dataframe(data=df, width='stretch', column_config=config)
