# -*- coding: utf-8 -*-
"""prototype_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X46BCEh56zmU1MxbTUO5yMC38SswgTwn
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

# Title of the app
st.title("Who is likely to chrun - and when?")

# Cached function to read CSVs
@st.cache_data(show_spinner="Parsing uploaded data...")
def load_csv_file(uploaded_file):
    if uploaded_file is None:
        return None
    return pd.read_csv(uploaded_file)

# Sidebar section for file inputs
st.sidebar.header("Data Import")
st.sidebar.markdown("Upload all 4 CSV files to run analysis.")

sf_file = st.sidebar.file_uploader("1. Salesforce Data", type=["csv"])
omni_file = st.sidebar.file_uploader("2. Omni Data", type=["csv"])
pendo_file = st.sidebar.file_uploader("3. Pendo Data", type=["csv"])
zendesk_file = st.sidebar.file_uploader("4. Zendesk Support Data", type=["csv"])

# Load files into cache
df_sf = load_csv_file(sf_file)
df_omni = load_csv_file(omni_file)
df_pendo = load_csv_file(pendo_file)
df_zendesk = load_csv_file(zendesk_file)

# List of loaded DataFrames for quick validation
all_dfs = [df_sf, df_omni, df_pendo, df_zendesk]
loaded_count = sum(1 for df in all_dfs if df is not None)

# Main Page Area
if loaded_count == 4:
    st.success("All 4 data sources loaded successfully!")
else:
    st.info(f"Please upload all 4 files using the sidebar to begin analysis. ({loaded_count}/4 loaded)")

    # Show status list in main view 
    st.markdown("### Missing Datasets:")
    st.markdown(f"- **Salesforce Data:** {'Ready' if df_sf is not None else 'Pending upload'}")
    st.markdown(f"- **Usage Data:** {'Ready' if df_omni is not None else 'Pending upload'}")
    st.markdown(f"- **Support Data:** {'Ready' if df_pendo is not None else 'Pending upload'}")
    st.markdown(f"- **Billing Data:** {'Ready' if df_zendesk is not None else 'Pending upload'}")

# Ensures that all dataframes exist before processing
if all(df is not None for df in [df_sf, df_omni, df_pendo, df_zendesk]):

    # Standardize 'customer_id' across all datasets
    dfs = [df_sf, df_omni, df_pendo, df_zendesk]
    for dataset in dfs:
        if 'customer_id' in dataset.columns:
            dataset['customer_id'] = dataset['customer_id'].astype(str).str.strip().str.upper()

    # Sequential Outer Merge
    df = df_sf.merge(df_omni, on='customer_id', how='outer') \
              .merge(df_pendo, on='customer_id', how='outer') \
              .merge(df_zendesk, on='customer_id', how='outer')

    # Vectorized Risk Score Calculation
    conditions = [
        (df['days_to_renewal'] <= 30) & (df['usage_change_90d_pct'] <= -25.0),
        (df['days_to_renewal'] <= 90) & (df['usage_change_90d_pct'] <= 5.0)
    ]
    levels = ['High', 'Medium']
    
    # Assigns 'Low' as default if neither condition above is met
    df['risk_score'] = np.select(conditions, levels, default='Low')

    # --- TOP SECTION: Visual Dashboard ---
    col1, col2 = st.columns([1, 1])

    with col1:
        st.subheader("Risk Score Distribution")
        
        # Color palette map for risk tiers
        color_map = {
            "High": "#EF553B",    # Red
            "Medium": "#FECB52",  # Yellow/Orange
            "Low": "#00CC96"      # Green
        }

        # Plotly Pie Chart
        fig = px.pie(
            df,
            names='risk_score',
            title='Percentage of Customers by Risk Level',
            color='risk_score',
            color_discrete_map=color_map,
            hole=0.4  # Creates a clean donut chart style
        )
        fig.update_traces(textinfo='percent+label+value', hovertemplate="%{label}: %{value} customers (%{percent})")
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        st.subheader("Key Metrics")
        total_cust = len(df)
        high_risk_count = len(df[df['risk_score'] == 'High'])
        med_risk_count = len(df[df['risk_score'] == 'Medium'])
        
        st.metric("Total Customers", f"{total_cust:,}")
        st.metric("High Risk Customers", f"{high_risk_count:,}", delta=f"{high_risk_count/total_cust:.1%}", delta_color="inverse")
        st.metric("Medium Risk Customers", f"{med_risk_count:,}", delta=f"{med_risk_count/total_cust:.1%}", delta_color="off")

    st.divider()

# --- BOTTOM SECTION: Filtered Data Table ---
    st.subheader("Customer Details")
    
    # Filter only specific columns to display on screen
    display_columns = [
        "customer_id", 
        "customer_name", 
        "renewal_date", 
        "days_to_renewal", 
        "annual_revenue", 
        "risk_score"
    ]
    
    # Keep only columns that exist in the merged dataframe
    final_cols = [col for col in display_columns if col in df.columns]
    df_display = df[final_cols]

    # Column Configuration & Display
    config = {
        "customer_id": st.column_config.TextColumn("Customer ID", width="medium"),
        "customer_name": st.column_config.TextColumn("Customer Name", width="medium"),
        "renewal_date": st.column_config.DateColumn("Renewal Date", format="MMM, DD YYYY"),
        "days_to_renewal": st.column_config.NumberColumn("Days to Renewal", format="%d days"),
        "annual_revenue": st.column_config.NumberColumn("Annual Revenue ($)", format="$%d"),
        "risk_score": st.column_config.TextColumn("Risk Score")
    }

    st.subheader("Customer Risk Summary")
    st.dataframe(df_display, width="stretch", use_container_width=True, column_config=config)

else:
    st.info("Please upload all required CSV files to run the merge and risk calculation.")

